CREATE DATABASE IF NOT EXISTS employees;

USE employees;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(20) NOT NULL,
  email VARCHAR(60) NOT NULL,
  country VARCHAR(30) NOT NULL
);
